version: '3.8'

services:
  go-api:
    build:
      context: ./api-go
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_API_URL=http://node-api:3001
    networks:
      - app-network

  node-api:
    build:
      context: ./api-nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_GO_API_URL=http://localhost:3000
      - VITE_NODE_API_URL=http://localhost:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
